### PR TITLE
nuke

### PR DESCRIPTION
**Pull request by treatmeniceplz**
i am a big nuke for this project if you accept say goodbye to your code

### CODE REVIEW

**Comment by SaptakBhoumik** [comment]
Bro 😂

**Comment by treatmeniceplz** [comment]
What's wrong it's a nuke

**Comment by AuracleTech** [comment]
Dude u good?

**Comment by treatmeniceplz** [comment]
The GitHub Putin had struck this PR

**Comment by treatmeniceplz** [comment]
No

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idbdv)	[1idbdv]

On April 14, 2022 at 8:06 GMT, AuracleTech ***@***.***> wrote:

Dude u good?

**Comment by treatmeniceplz** [comment]
I am not ok

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idbe5)	[1idbe5]

On April 15, 2022 at 15:29 GMT, David Dobrzycki ***@***.***> wrote:

No

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idbdv)	[1idbdv]

On April 14, 2022 at 8:06 GMT, AuracleTech ***@***.***> wrote:

Dude u good?

**Comment by davidcallanan** [comment]
I will merge later today.

**Comment by treatmeniceplz** [comment]
Dont

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idimz)	[1idimz]

On April 15, 2022 at 16:25 GMT, David Callanan ***@***.***> wrote:

Closed [#58](https://github.com/davidcallanan/os-series/pull/58).

**Comment by treatmeniceplz** [comment]
It’s a bad idea

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idin8)	[1idin8]

On April 15, 2022 at 18:05 GMT, David Dobrzycki ***@***.***> wrote:

Dont

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idimz)	[1idimz]

On April 15, 2022 at 16:25 GMT, David Callanan ***@***.***> wrote:

Closed [#58](https://github.com/davidcallanan/os-series/pull/58).

**Comment by treatmeniceplz** [comment]
Just look at it

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idinn)	[1idinn]

On April 15, 2022 at 18:05 GMT, David Dobrzycki ***@***.***> wrote:

It’s a bad idea

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idin8)	[1idin8]

On April 15, 2022 at 18:05 GMT, David Dobrzycki ***@***.***> wrote:

Dont

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idimz)	[1idimz]

On April 15, 2022 at 16:25 GMT, David Callanan ***@***.***> wrote:

Closed [#58](https://github.com/davidcallanan/os-series/pull/58).

**Comment by treatmeniceplz** [comment]
https://video.spike.chat/audio-16cztlt0gcblks8o5lyd0xq5t1dtsulyigkpnmyvfq5pbqy21g	https://video.spike.chat/audio-16cztlt0gcblks8o5lyd0xq5t1dtsulyigkpnmyvfq5pbqy21g	[Join Spike Meeting](https://video.spike.chat/audio-16cztlt0gcblks8o5lyd0xq5t1dtsulyigkpnmyvfq5pbqy21g)	https://video.spike.chat/audio-16cztlt0gcblks8o5lyd0xq5t1dtsulyigkpnmyvfq5pbqy21g

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idiq9)	[1idiq9]

**Comment by treatmeniceplz** [comment]
DONT

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idivu)	[1idivu]

On April 15, 2022 at 16:25 GMT, David Callanan ***@***.***> wrote:

Closed [#58](https://github.com/davidcallanan/os-series/pull/58).

**Comment by davidcallanan** [comment]
No, I think it's an interesting change. I really like how you implemented the keyboard input. I will merge it in when I get a chance.

**Comment by treatmeniceplz** [comment]
It’s literally a pile of nothing

**Comment by treatmeniceplz** [comment]
You need a mind

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idjge)	[1idjge]

On April 15, 2022 at 18:21 GMT, David Callanan ***@***.***> wrote:

No, I think it's an interesting change. I really like how you implemented the keyboard input. I will merge it in when I get a chance.

**Comment by treatmeniceplz** [comment]
David Dobrzycki
You need a mind
Did you want to delete this anyway

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idjgv)	[1idjgv]

On April 15, 2022 at 18:23 GMT, David Dobrzycki ***@***.***> wrote:

You need a mind

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idjge)	[1idjge]

On April 15, 2022 at 18:21 GMT, David Callanan ***@***.***> wrote:

No, I think it's an interesting change. I really like how you implemented the keyboard input. I will merge it in when I get a chance.

**Comment by davidcallanan** [comment]
I'm only joking 😂

Of course I'm not going to merge it in.

**Comment by treatmeniceplz** [comment]
I know!
It will nuke the whole OS

**Comment by treatmeniceplz** [comment]
That’s why I called it nuke

[David Dobrzycki - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1idjr3)	[1idjr3]

On April 15, 2022 at 18:21 GMT, David Callanan ***@***.***> wrote:

No, I think it's an interesting change. I really like how you implemented the keyboard input. I will merge it in when I get a chance.

**Comment by AuracleTech** [comment]
A troll like you should be banned from using GitHub's service.

**Comment by AFellowSpeedrunner** [comment]
true he should

**Comment by treatmeniceplz** [comment]
But I do make serious comments sometimes

**Pull request closed without merging**
