### PR TITLE
Doom

### PR DESCRIPTION
**Pull request by jbreu**

### CODE REVIEW

**Comment by AFellowSpeedrunner** [comment]
did you just decide to rewrite all of this in rust and then put doom in it? legend... this should be merged in.

**Comment by jbreu** [comment]
@AFellowSpeedrunner haha yes, it’s a dad‘s spare time project. I jost don’t get GitHub’s UI so sometimes I accidentally open PRs to the original repo

**Comment by AFellowSpeedrunner** [comment]
> @AFellowSpeedrunner haha yes, it’s a dad‘s spare time project. I jost don’t get GitHub’s UI so sometimes I accidentally open PRs to the original repo

ah makes sense, I'm working on my own Rust kernel and OS after realising this would never be finished. it's using base code from the Rust OS tutorial but I'm expanding upon it. I've got a shell added and proper backspaces. it's amazing to see what you've done though, honestly.

**Comment by jbreu** [comment]
@AFellowSpeedrunner thanks, your work is pretty impressive, too. Let me know when you have progressed with your studies, maybe u got a job for you 😅

**Comment by AFellowSpeedrunner** [comment]
> @AFellowSpeedrunner thanks, your work is pretty impressive, too. Let me know when you have progressed with your studies, maybe u got a job for you 😅

thank you! It's still in very early development but I'm making slow progress. It's better than getting nowhere. I'll let you know. I also post updates about my kernel OS to my Mastodon page.

**Pull request closed without merging**
